sudo: required
services:
  - docker

before_install:
  - docker build -t stalisetty/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true stalisetty/docker-react npm run test --  --coverage
